### ISSUE TITLE
Transfer to FLORIS v4

### ISSUE THREAD

**Issue by MarcusBecker-GitHub** [TUDelft-DataDrivenControl/OFF#12]
# FLORIS v4 adaptation
FLORIS v4 was released and OFF will change its interface to the new code.

Necessary changes entail
- [x] New wake model
- [x] New wake solver interface (?)
- [x] Adapted input files
- [ ] tbd

Possible extensions could include the use of new FLORIS v4 features. This includes, but is not exclusive to
- [ ] turning off turbines
- [ ] AWM control

**Comment by rafmudaf** [comment]
Hey @MarcusBecker-GitHub I'm happy to help here however I can. Just let me know if / how I can help.

**Comment by MarcusBecker-GitHub** [comment]
Thanks for the offer @rafmudaf !
Today I got it working - the main "issues" were that OFF generates the input files for FLORIS, that needed a bit of fixing, and how the results are retrieved. But everything was resolved fairly quick. Overall a smooth transition.
Now I am working on the flow field visualization.

**Comment by MarcusBecker-GitHub** [comment]
Plotting works!
Each tile is an individual FLORIS simulation used to approximate the flow conditions at the location of the respective turbine.
The code automatically assigns the grid points to each simulation, only a sufficient resolution is needed.
There is even a version of the plot where every FLORIS simulation has one of 5 colormaps, to highlight that different simulations are taking place at the same time.

Normal tile plot
![flow_field_700 0](https://github.com/TUDelft-DataDrivenControl/OFF/assets/75479673/68a7cf2a-5118-4363-9b55-56026ec35f2d)

5-color tile plot (not scaled yet)
![flow_field_900 0_landscape](https://github.com/TUDelft-DataDrivenControl/OFF/assets/75479673/38431175-ae69-4731-ab32-66f0e31e0ceb)
